name: Test Lighthouse Check Status
on:
  push:
    branches: 
      - master

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm install
    - name: Run Lighthouse
      uses: foo-software/lighthouse-check-action@master
      id: lighthouseCheck
      with:
        urls: 'https://www.foo.software,https://www.foo.software/contact'
    - name: Handle Lighthouse Check results
      uses: ./
      with:
        lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
        minAccessibilityScore: 50
        minBestPracticesScore: 50
        minPerformanceScore: 50
        minProgressiveWebAppScore: 50
        minSeoScore: 50
